# To change this template, choose Tools | Templates
# and open the template in the editor.
module GameSettings
  

  SCREEN_X = 640
  SCREEN_Y = 480
  BGX = 1280
  BGY = 960
  MENU_LAYER_INSET = 25
  MENU_TEXT_INSET = 10
  NOTIFICATION_TEXT_INSET = 10
  MENU_LINE_SPACING = 25
  NOTIFICATION_LINE_SPACING = 25
  MENU_TEXT_WIDTH = 100
  LAYER_INSET = 25
  TEXT_INSET = 10
  HERO_START_BATTLE_PTS = 1000
  HERO_BATTLE_PTS_RATE = 1.1
  MONSTER_START_BATTLE_PTS = 800
  MONSTER_BATTLE_PTS_RATE = 1.0
  READINESS_POINTS_PER_SECOND = 1000
  READINESS_POINTS_NEEDED_TO_ACT = 3000
  DEFAULT_ACTION_COST = 2500
  ATTACK_ACTION_COST = 2000
  ITEM_ACTION_COST = 1500
  NOOP_ACTION_COST = 1000

  OPEN_TREASURE = 'O'
  MONSTER_X = 32
  MONSTER_Y = 32
  NOTIFICATION_LAYER_WIDTH = SCREEN_X/3
  NOTIFICATION_LAYER_HEIGHT = SCREEN_Y/3
  NOTIFICATION_LAYER_INSET_X = 2 * SCREEN_X/3
  NOTIFICATION_LAYER_INSET_Y = 2 * SCREEN_Y/3
  TICKS_TO_DISPLAY_NOTIFICATIONS = 125
  GAME_TITLE = "splatwars"

  STATUS_WIDTH = 100
  STATUS_HEIGHT = 300
  MENU_DETAILS_INSET_X = 300
  MENU_DETAILS_INSET_Y = 25
  MENU_OPTIONS_INSET_X = 400
  MENU_OPTIONS_INSET_Y = 25


  BATTLE_INVENTORY_XC = 400
  BATTLE_INVENTORY_XF = 0
  BATTLE_INVENTORY_YC = 25
  BATTLE_INVENTORY_YF = 25
  DOWNKEY = :always_down

  WEAPON_UP_OFFSET_X = -15
  WEAPON_UP_OFFSET_Y = -45
  WEAPON_DOWN_OFFSET_X = -15
  WEAPON_DOWN_OFFSET_Y = 20
  WEAPON_LEFT_OFFSET_X = -45
  WEAPON_LEFT_OFFSET_Y = -15
  WEAPON_RIGHT_OFFSET_X = 0
  WEAPON_RIGHT_OFFSET_Y = -10
  WEAPON_UP_ANGLE = 270
  WEAPON_DOWN_ANGLE = 120
  WEAPON_LEFT_ANGLE = -10
  WEAPON_RIGHT_ANGLE = 180
  WEAPON_ROTATION = 90
  NUM_SLOTS = 5
  FONT_DEPTH = 24
  MS_PER_SEC = 1000
  INTERACTION_DISTANCE_THRESHOLD = 80 #XXX tweak this, currently set to 1/2 a tile


  FRAME_SWITCH_THRESHOLD = 0.40
  ANIMATION_FRAMES = 4

end